import fs from 'fs';
import path from 'path';
import { getDataPath } from './data-path';

/**
 * Initialize data files in Railway volume or local data directory.
 * Copies static data files from source to destination if they don't exist.
 */
export async function initializeDataFiles(): Promise<void> {
    try {
        // Determine destination data path: Railway volume mount or local data directory
        const destinationDataPath = getDataPath();

        // Determine source data path (from repo)
        // In production build, source files are in the same location as the built server
        // We need to find the data directory relative to the server files
        const sourceDataPath = path.join(process.cwd(), 'data');

        console.log(`[DataInit] Destination data path: ${destinationDataPath}`);
        console.log(`[DataInit] Source data path: ${sourceDataPath}`);

        // Ensure destination directory exists
        if (!fs.existsSync(destinationDataPath)) {
            console.log(`[DataInit] Creating destination directory: ${destinationDataPath}`);
            fs.mkdirSync(destinationDataPath, { recursive: true });
        }

        // List of static files to copy (only if they don't exist in destination)
        const staticFiles = [
            'paramV4.json',
            'microsaas-principles.txt',
            'sectors.json',
        ];

        let copiedCount = 0;
        let skippedCount = 0;
        let errorCount = 0;

        for (const filename of staticFiles) {
            const sourcePath = path.join(sourceDataPath, filename);
            const destPath = path.join(destinationDataPath, filename);

            // Skip if file already exists in destination (preserve volume persistence)
            if (fs.existsSync(destPath)) {
                console.log(`[DataInit] Skipping ${filename} (already exists in destination)`);
                skippedCount++;
                continue;
            }

            // Check if source file exists
            if (!fs.existsSync(sourcePath)) {
                console.warn(`[DataInit] Warning: Source file not found: ${sourcePath}`);
                errorCount++;
                continue;
            }

            // Copy file
            try {
                fs.copyFileSync(sourcePath, destPath);
                console.log(`[DataInit] Copied ${filename} to destination`);
                copiedCount++;
            } catch (error) {
                console.error(`[DataInit] Error copying ${filename}:`, error);
                errorCount++;
            }
        }

        console.log(`[DataInit] Initialization complete: ${copiedCount} copied, ${skippedCount} skipped, ${errorCount} errors`);

        // Note about sectors_aggregated_metrics.json
        const sectorsAggregatedPath = path.join(destinationDataPath, 'sectors_aggregated_metrics.json');
        if (!fs.existsSync(sectorsAggregatedPath)) {
            console.warn(`[DataInit] Warning: sectors_aggregated_metrics.json not found in destination.`);
            console.warn(`[DataInit] This file needs to be generated by running the aggregation script or manually added to the volume.`);
            console.warn(`[DataInit] The /api/sectors/aggregated endpoint will return 404 until this file exists.`);
        }

    } catch (error) {
        console.error('[DataInit] Fatal error during data file initialization:', error);
        // Don't throw - allow server to start even if initialization fails
        // The application will handle missing files gracefully
    }
}

